# Generated by Django 3.1.1 on 2020-09-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('b_date', models.DateField(verbose_name='Date of birth')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
