# Generated by Django 3.1.1 on 2020-09-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=30, verbose_name='Phone number'),
        ),
    ]
