# Generated by Django 3.1.1 on 2020-09-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_googlelead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=4, verbose_name='Method')),
                ('path', models.CharField(max_length=100, verbose_name='Path')),
                ('response_time', models.CharField(max_length=100, verbose_name='Response time')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
