# Generated by Django 3.1.1 on 2020-09-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_logger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=1024)),
                ('sends', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
